import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProviders } from "@/components/Providers/theme-provider";
import NavbarComponent from "@/components/common/NavbarComponent";
import QueryClientProviderWrapper from "@/components/Providers/QuertProvider";
import ReduxProvider from "@/components/Providers/ReduxProvider";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import SessionProviders from "@/components/Providers/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProviders>
          <ThemeProviders >
            <QueryClientProviderWrapper>
              <ReduxProvider>
                <NavbarComponent />
                <main>{children}</main>
                <Toaster position="top-right" />
              </ReduxProvider>
            </QueryClientProviderWrapper>
          </ThemeProviders>
        </SessionProviders>
      </body>
    </html>
  );
}
